---
apiVersion: v1
kind: Pod
metadata:
  name: playpod
  labels:
    name: playpod
spec:
  containers:
  - name: playpod
    image: nginx
    resources:
      limits:
        memory: "100Mi"
        cpu: "300m"
    ports:
      - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-frontend
  template:
    metadata:
      labels:
        app: http-frontend
    spec:
      containers:
      - name: http-frontend
        image: httpd:latest
        resources:
          limits:
            memory: "100Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
---


    
