apiVersion: apps/v1
kind: Deployment
metadata:
  name: playbox
spec:
  selector:
    matchLabels:
      app: playbox
  template:
    metadata:
      labels:
        app: playbox
    spec:
      containers:
      - name: playbox
        image: busybox
        command: ["echo", "$(value1)"]
        envFrom:
          - configMapRef:
              name: colors
          - secretRef:
              name: busy-secret
        resources:
          limits:
            memory: "100Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: colors
data:
  color1: blue
  color2: green
---
apiVersion: v1
kind: Secret
metadata:
  name: busy-secret
type: Opaque
data:
  value1: dG9wc2VjcmV0
